### ISSUE TITLE
Tags must be between 2 and 0 letters long.

### ISSUE THREAD

**Issue by fardina** [svivian/q2a-tagging-tools#28]
Hi Scott
Thank you for your great plugin.
I think there is a little bug in the tagging tools plugin.
Here is how to reproduce the error:
Set minimum length to 2 and max length=0(which means no limit)
Don't allow creating new tags(1000points needed)

Ask a question and click on the (matched tags while typing) to insert tags, for example the choosen tags would be like "plugin core ". After submiting there is ` Tags must be between 2 and 0 letters long.`

![taggingt](https://user-images.githubusercontent.com/13521621/50006283-7ff06780-ffc2-11e8-8482-bef1f2a3ce11.png)
I realized the reason is when you choose between matched tags there is a space after each tags. 
if you delete the space from the last tag(i.e. like "plugin core") then it doesn't get the error.

Also it would be great if you convert 0 to 'unlimitted' when showing the error message. At the moment it is confusing for users.

Thanks.

**Comment by svivian** [comment]
Should be fixed in the latest commit, can you download and confirm?

**Comment by fardina** [comment]
It works very well. Thanks.

**Comment by svivian** [comment]
OK great, thanks! I've added a v1.9.1 release.

**Comment by fardina** [comment]
I checked the plugin with admin account and moderators. But now I discovered the problem still exists for guests(non logged in users) and registered users:
![tagging tools](https://user-images.githubusercontent.com/13521621/50710907-96e61f00-1081-11e9-9233-d4b72b0f4a45.png)
My Settings:

Minimum tag length |  2
Maximum tag length | 0
Prevent new users from creating new tags |  Yes
Minimum reputation to create new tags |  1000

**Comment by svivian** [comment]
Oh, it was counting the extra space on the end as a blank tag. I've made another update that fixes this, can you test again and confirm? Thanks.

**Comment by fardina** [comment]
It's working very well for me. Thank you.

**Comment by svivian** [comment]
Excellent, thanks! I've released v1.9.2.
